# Welcome to Jekyll!

# Website settings
title: "Robotenique's Home"
description: "Juliano Garcia's personal website."
keywords: "Robotenique,Python,programming,development,github,ime-usp,computer,science"
baseurl: "/"
url: "-"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Juliano Garcia'
  first_name: 'Juliano'
  last_name: ''
  email: 'julianogarcia_1997@hotmail.com'
  facebook_username: 'julianoGarciaO'
  github_username: 'robotenique'
  head_img: 'static/img/landing/robt.png'
  desc1: 'Hi, I am Juliano Garcia, a Computer Science student, and this is my personal page. '
  desc2: 'My main areas of interest are AI and machine learning, the Python programming language, functional programming, applications of linear algebra and ∆ ＶＡＰＯＲＷＡＶΞ ∆  :)'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'contact'
    i18n: 'nav.link'
    name: 'Contact'
    tpl: 'links.html'
    css: 'contact'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'


# comment
disqus:
  name: robotenique
  public_key: X2wAYdAG0a799k7zxvSaRmPOf3zbBTtDGrgou6Xwze9cFgcMrbqOM2OA6CMvg0NF


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
